# AI Smart Shopping Basket Optimizer

## Notebook 01: Data Understanding

### Objective

The objective of this notebook is to understand the BigBasket product dataset, inspect its structure, identify missing values and duplicates, and perform initial data cleaning before analysis.

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv(
    r"C:\Users\sampa\Desktop\AI-Smart-Shopping-Basket-Optimizer\data\raw\bigbasket\BigBasket Products.csv"
)

In [4]:
df.head()

,index,product,category,sub_category,brand,sale_price,market_price,type,rating,description
0,1,Garlic Oil - Vegetarian Capsule 500 mg,Beauty & Hygiene,Hair Care,Sri Sri Ayurveda,220.0,220.0,Hair Oil & Serum,4.1,This Product contains Garlic Oil that is known...
1,2,Water Bottle - Orange,"Kitchen, Garden & Pets",Storage & Accessories,Mastercook,180.0,180.0,Water & Fridge Bottles,2.3,"Each product is microwave safe (without lid), ..."
2,3,"Brass Angle Deep - Plain, No.2",Cleaning & Household,Pooja Needs,Trm,119.0,250.0,Lamp & Lamp Oil,3.4,"A perfect gift for all occasions, be it your m..."
3,4,Cereal Flip Lid Container/Storage Jar - Assort...,Cleaning & Household,Bins & Bathroom Ware,Nakoda,149.0,176.0,"Laundry, Storage Baskets",3.7,Multipurpose container with an attractive desi...
4,5,Creme Soft Soap - For Hands & Body,Beauty & Hygiene,Bath & Hand Wash,Nivea,162.0,162.0,Bathing Bars & Soaps,4.4,Nivea Creme Soft Soap gives your skin the best...

In [5]:
df.shape

(27555, 10)

In [6]:
df.columns

Index(['index', 'product', 'category', 'sub_category', 'brand', 'sale_price',
       'market_price', 'type', 'rating', 'description'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27555 entries, 0 to 27554
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   index         27555 non-null  int64
 1   product       27554 non-null  object
 2   category      27555 non-null  object
 3   sub_category  27555 non-null  object
 4   brand         27554 non-null  object
 5   sale_price    27555 non-null  float64
 6   market_price  27555 non-null  float64
 7   type          27555 non-null  object
 8   rating        18929 non-null  float64
 9   description   27440 non-null  object
dtypes: float64(3), int64(1), object(6)
memory usage: 2.1+ MB

In [8]:
df.describe()

             index    sale_price  market_price        rating
count  27555.00000  27555.000000  27555.000000  18929.000000
mean   13778.00000    322.514808    382.056664      3.943410
std     7954.58767    486.263116    581.730717      0.739063
min        1.00000      2.450000      3.000000      1.000000
25%     6889.50000     95.000000    100.000000      3.700000
50%    13778.00000    190.000000    220.000000      4.100000
75%    20666.50000    359.000000    425.000000      4.300000
max    27555.00000  12500.000000  12500.000000      5.000000

In [9]:
df.isnull().sum()

index              0
product            1
category           0
sub_category       0
brand              1
sale_price         0
market_price       0
type               0
rating          8626
description      115
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.drop("index", axis=1, inplace=True)

In [12]:
df[df["product"].isnull()]

,product,category,sub_category,brand,sale_price,market_price,type,rating,description
14363,NaN,Beverages,Coffee,Cothas Coffee,200.0,240.0,Ground Coffee,4.2,Cothas Specialty Blend Coffee and Chicory incl...

In [13]:
df[df["brand"].isnull()]

,product,category,sub_category,brand,sale_price,market_price,type,rating,description
9765,Food Package - Medium,Cleaning & Household,"Disposables, Garbage Bag",NaN,50.0,50.0,"Aluminium Foil, Clingwrap",NaN,NaN

In [14]:
df_clean = df.dropna(subset=["product", "brand"])

In [15]:
df_clean.isnull().sum()

product            0
category           0
sub_category       0
brand              0
sale_price         0
market_price       0
type               0
rating          8625
description      114
dtype: int64

In [16]:
df_clean.to_csv(
    r"C:\Users\sampa\Desktop\AI-Smart-Shopping-Basket-Optimizer\data\processed\bigbasket_cleaned.csv",
    index=False
)

In [1]:
import pandas as pd

df = pd.read_csv(r"C:\Users\sampa\Desktop\AI-Smart-Shopping-Basket-Optimizer\data\processed\bigbasket_cleaned.csv")

print(df.columns.tolist())
print(df.shape)

['product', 'category', 'sub_category', 'brand', 'sale_price', 'market_price', 'type', 'rating', 'description']
(27553, 9)